language: node_js
node_js:
  - "11"

notifications:
  email: false

cache: npm

install:
  - npm install

script:
  - npm run lint
  - npm run testformat
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: deploy
